# Generated by Django 4.2 on 2024-07-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='genericText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='genericChar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kollege',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kollege',
            name='genericChar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='genericChar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
