# Generated by Django 4.2 on 2025-10-19 05:28

import core.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreportimage',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventreportimage',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventreport', to='core.event'),
        ),
        
      #  migrations.AlterField(
       #     model_name='kollege',
        #    name='crm',
         #   field=models.CharField(default=0, max_length=15, unique=True),
        #),
        
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/miguel/Dev/bdtest/digproj/media'), upload_to=core.models.temp_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempimages', to='core.event')),
            ],
        ),
    ]
