# Generated by Django 2.2.4 on 2022-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailfromsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='kollege',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
