# Generated by Django 4.2 on 2025-02-02 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_eventreport_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
