# Generated by Django 4.2 on 2025-02-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eventreport_indication_alter_event_kollege_and_more'),
        ('core', '0008_alter_eventreport_event'),
    ]

    operations = [
    ]
