"""
Django settings for digproj project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from django.core.files.storage import FileSystemStorage
import os
from decouple import config
#from dj_database_url import parse as dburl
from corsheaders.defaults import default_headers

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# Chat End-To-End Temp Storage.doc

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# directory where temporary capture images are stored
TEMP_MEDIA_ROOT = MEDIA_ROOT #os.path.join(MEDIA_ROOT, 'temp_images')
# FileSystemStorage instance used for TemporaryImage fields
TEMP_MEDIA_STORAGE = FileSystemStorage(location=TEMP_MEDIA_ROOT)
# Path to save temp images in the local intranet.
TEMP_IMAGE_LOCAL_PATH = TEMP_MEDIA_ROOT #os.path.join(MEDIA_ROOT, 'temp_images') #"/mnt/intranet/temp_images/"

ALLOWED_HOSTS = [
    '52.44.41.170', #AWS Elastic IP 26-12-24 for instance digproj1224
    '3.230.207.81', #AWS Elastic IP devDigproj1224
    'digest.com.br',
    'api.digest.com.br',
    'dev.digest.com.br',
    'localhost',
    '127.0.0.1',
]

#evironment vars done (DEBUG, SECRET_KEY, DB, EMAIL) with decouple.config
#stored at .env (must go to .gitignore)

DEBUG = config('DEBUG', default=False, cast=bool)
SECRET_KEY = config('SECRET_KEY')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core',
    'django_filters',
#   'storages',
    'user',
    'persona',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DEFAULT_AUTO_FIELD='django.db.models.AutoField' 

WSGI_APPLICATION = 'digproj.wsgi.application'
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_URL').split('/')[-1],
        'USER': config('DATABASE_URL').split('//')[1].split(':')[0],
        'PASSWORD': config('DATABASE_URL').split(':')[2].split('@')[0],
        'HOST': config('DATABASE_URL').split('@')[1].split(':')[0],
        'PORT': config('DATABASE_URL').split(':')[-1].split('/')[0],
        'CONN_MAX_AGE': 600,
    }
}
'''
############## For local DB, localhost ###########
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dig1224_test',
        'USER': '',
        'PASSWORD': config('PW_LOCAL'),
        'HOST': 'localhost',
        'PORT': '5432',
     }
}
##################################################

#SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"

#CORS_ORIGIN_ALLOW_ALL = True

############ Necessary #############
CORS_ALLOWED_ORIGINS = [
    'https://digest.com.br',
    'http://localhost:4200',
]

CORS_ALLOW_HEADERS = list(default_headers) + ['CurrentUser',]
#CSRF_TRUSTED_ORIGINS = [
#    'https://api.digest.com.br',
#]

#CSRF_COOKIE_SECURE = True
#SESSION_COOKIE_SECURE = True

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

AUTH_USER_MODEL = 'core.User'

EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

EMAIL_HOST_USER = 'miguel.sza@gmail.com'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Compress static files for serving
# https://warehouse.python.org/project/whitenoise
'''
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}
'''

""" ChatGPT 10-08-2025"""

INSTALLED_APPS += ['storages']
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME')
AWS_QUERYSTRING_AUTH = True   # generate signed URLs

AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}


"""Added 22-12-25"""

#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True


