# Generated by Django 4.2 on 2024-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_generictext_eventreport_genericchar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
