# Generated by Django 4.2 on 2024-12-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_partner_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genericChar1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='registerdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
