# Generated by Django 4.2 on 2025-02-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventreport_indication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_eventreport', to='core.event'),
        ),
    ]
