# Generated by Django 4.2 on 2025-02-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20250202_2246'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='kollege',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='partner',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='persona',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='procedure',
            index_together=set(),
        ),
    ]
